language: node_js
node_js:
  - '6'
branches:
  only:
  - master
before_install:
  - npm install -g firebase-tools
install:
  - echo "test build phase"
  - ls
  - npm install
  - npm run build
before_deploy: "echo 'installing firebase functions'"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "userddata"
  skip_cleanup: true
after_success:
  - firebase deploy --project userddata --only functions